name: hello_altstore_app # Nome do seu projeto Flutter
description: Um aplicativo Flutter de demonstração para AltStore.

# Prevenir publicação acidental em pub.dev.
publish_to: 'none'

# A versão aqui (ex: 1.0.0) será usada como base para o versionamento incremental.
# O número após o '+' (build number) será substituído pelo github.run_number no IPA.
version: 1.0.0+1 

# Restrição do SDK do Dart - importante para o 'flutter pub get'
environment:
  sdk: ">=3.8.0 <4.0.0" # Ou a versão mais recente compatível com o Flutter Stable (ex: ^3.3.0, ^3.4.0)

dependencies:
  flutter:
    sdk: flutter

  # Exemplo de outra dependência, como ícones do Cupertino
  cupertino_icons: ^1.0.6 # Use a versão mais recente
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  http: ^1.2.1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Use a versão mais recente do lints

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/app_icon.png # Se você hospedar seu ícone no projeto