name: hello_altstore_app
description: Um simples aplicativo Flutter "Hello World" para AltStore.

# Prevenir publicação acidental em pub.dev.
publish_to: 'none' # Remover esta linha se você quiser publicar em pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ajuste conforme a sua versão do Dart/Flutter

dependencies:
  flutter:
    sdk: flutter

  # Adicione outras dependências aqui, se necessário.
  # Exemplo: cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Ou a versão mais recente

flutter:
  uses-material-design: true

  # Para adicionar assets à sua aplicação, adicione uma seção assets, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
