# Nome do arquivo: pubspec.yaml
# (Localizado na raiz do seu projeto Flutter)

name: hello_altstore_app # Ou o nome real do seu app Flutter
description: Um simples aplicativo Flutter "Hello World" para AltStore.

# Prevenir publicação acidental em pub.dev.
publish_to: 'none'

version: 1.0.0+1 # A versão do seu app

# ESTA É A SEÇÃO CRÍTICA PARA O ERRO QUE VOCÊ ESTAVA VENDO
environment:
  sdk: '^3.8.0' # <<< GARANTA QUE ESTEJA ASSIM OU SIMILAR (EX: ^3.3.0 dependendo do Flutter stable)

dependencies:
  flutter:
    sdk: flutter

  # Adicione outras dependências aqui, como cupertino_icons se estiver usando
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Ou ^3.0.0 ou mais recente

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg