default_platform(:ios)

platform :ios do
  desc "Build the app without signing"
  lane :build_without_signing do
    gym(
    workspace: "Runner.xcworkspace",
    scheme: "Runner",
    export_method: "development",
    export_options: {
        compileBitcode: false,
        method: "development",
        signingStyle: "manual",
        teamID: "ABCDE12345", # <-- fictício
        manageAppVersionAndBuildNumber: false,
        stripSwiftSymbols: true
    },
    export_xcargs: "-allowProvisioningUpdates",
    output_directory: "./build/ios/ipa",
    clean: true,
    silent: true,
    skip_codesigning: true
    )
  end
end
