default_platform(:ios)

platform :ios do
  desc "Build the app without signing"
  lane :build_without_signing do
    gym(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      clean: true,
      export_method: "ad-hoc",
      export_options: {
        signingStyle: "manual",
        compileBitcode: false,
        method: "ad-hoc",
        provisioningProfiles: {},
        signingCertificate: "",
        teamID: ""
      },
      output_directory: "./build/ios/ipa",
      output_name: "app_without_signing.ipa",
      silent: true
    )
  end
end
