name: Build iOS App (No Code Sign for AltStore)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign

      - name: Disable code signing in Xcode
        run: |
          cd ios
          # Forçar desabilitação de code signing no Xcode
          defaults write com.apple.dt.Xcode.plist IDEDisableAutomaticSigning YES

      - name: Generate IPA using Xcode (without code signing)
        run: |
          cd ios
          # Realiza o build do archive sem assinatura
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -archivePath build/ios/archive/Runner.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          # Gera o .ipa sem assinatura
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build/ios/ipa

      - name: Upload unsigned IPA for AltStore
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: build/ios/ipa/*.ipa
